"""empty message

Revision ID: 328d2bbeabfa
Revises: 
Create Date: 2023-01-11 15:54:41.101825

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "328d2bbeabfa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("surname", sa.String(length=80), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("employee")
    # ### end Alembic commands ###
